# Site settings
title: Nate Otto's Learning Path
description: A collection of badges
favicon:
baseurl:
url: 
rss_url: /pages/atom.xml
analytics_id: 'UA-63653234-1'

# Build settings
markdown: kramdown

# # Author settings
# author:
#   name: Nate Otto
#   title: Open Badges Evangelist
#   address: "Eugene, Oregon"
#   email: nate@ottonomy.net
#   link: http://ottonomy.net
#   weibo:
#   github: ottonomy
#   linkedin: 
#   twitter: ottonomy
#   gavatar: 
#   languages:
#   programmingSkills:
